name: Test

on:
  pull_request:
    branches:
      - release
      - develop

env:
  CARGO_TERM_COLOR: always
  TZ: America/Los_Angeles

jobs:
  Test:
    name: iMessage Exporter Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - run: rustup update stable && rustup default stable
      - run: cargo fmt --all --check
      - run: cargo clippy --workspace --all-targets -- -D warnings
      - run: cargo doc --no-deps --workspace
        env:
          RUSTDOCFLAGS: -D warnings
      - run: cargo test --workspace --all-targets --verbose
